# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "nfs-server"
  config.vm.provider "virtualbox" do |vb|
  	vb.name = "nfs-server"
  end
  config.vm.network "private_network", ip: "192.168.1.5"  
end