# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "control-node"
  config.vm.hostname = "control-node"
  config.vm.provider "virtualbox" do |vb|
  	vb.name = "control-node"
  end
  config.vm.network "private_network", ip: "192.168.33.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
end