- name: Upgrade de todos os pacotes do s.o
# modulo do ansible
  yum:
  # todos os pacotes
    name: '*'
    state: latest
- name: instalacao do git client
  yum:
  #nome do pacote
  name: git
  state: latest