# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "db01"
  config.vm.hostname = "db01"
  config.vm.network "private_network", ip: "192.168.33.4"
  config.vm.network "forwarded_port", guest: 3306, host:3306
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |vb|
  	vb.name = "db01"
  end   
end